stages:
  - linting

image: python:3.10.4-slim-bullseye

before_script:
  - apt-get update
  - apt-get install -y python3-pip
  - pip install pycodestyle

pycodestyle:
  stage: linting
  script:
    - echo "pycodestyle linting"
    - pycodestyle --max-line-length=120 .
